/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.miwashi.testfirst;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
